/*
 * File: app/model/UserModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RLM.model.UserModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            mapping: 'id',
            name: '#'
        },
        {
            mapping: 'account',
            name: '帐号'
        },
        {
            mapping: 'password',
            name: '密码'
        },
        {
            mapping: 'realName',
            name: '真名'
        },
        {
            mapping: 'sex',
            name: '性别'
        },
        {
            mapping: 'email',
            name: '邮箱'
        },
        {
            mapping: 'role',
            name: '角色'
        },
        {
            mapping: 'stuNo',
            name: '学号'
        },
        {
            mapping: 'startYear',
            name: '入学年份'
        },
        {
            mapping: 'mobilePhone',
            name: '电话'
        },
        {
            mapping: 'createTime',
            name: '创建时间'
        }
    ]
});