/*
 * File: app/view/AddUserWin.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RLM.view.AddUserWin', {
    extend: 'Ext.window.Window',

    height: 347,
    id: 'addUserWin',
    width: 344,
    layout: {
        type: 'fit'
    },
    title: '添加用户',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            buttons: [
                {
                    text: '确认',
                    action: 'okAction'
                },
                {
                    text: '取消',
                    action: 'cancelAction'
                }
            ],
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '帐号',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '真名',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '密码',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '邮箱',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '电话',
                            labelWidth: 60
                        },
                        {
                            xtype: 'radiogroup',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            fieldLabel: '性别',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '男'
                                },
                                {
                                    xtype: 'radiofield',
                                    margins: '0 0 0 25px',
                                    boxLabel: '女'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            title: '角色',
                            items: [
                                {
                                    xtype: 'radiogroup',
                                    fieldLabel: '角色',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: '学生'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: '教师'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: '管理员'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '学号',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: '入学年份',
                                    labelWidth: 60
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});