/*
 * File: app/view/CourseManageView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RLM.view.CourseManageView', {
    extend: 'Ext.panel.Panel',

    id: 'CourseManageModual',
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: '课程管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 0,
                    height: 98,
                    layout: {
                        columns: 4,
                        type: 'table'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '0 5px 0 0',
                            fieldLabel: '课程名称',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '课程描述',
                            labelWidth: 70
                        },
                        {
                            xtype: 'numberfield',
                            padding: '0 5px',
                            fieldLabel: '课时',
                            labelWidth: 85
                        },
                        {
                            xtype: 'numberfield',
                            padding: '0 0 0 5px',
                            fieldLabel: '学分',
                            labelWidth: 85
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px 0 0',
                            fieldLabel: '所属分类',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '创建者',
                            labelWidth: 70
                        },
                        {
                            xtype: 'datefield',
                            padding: '0 5px',
                            fieldLabel: '创建时间(起)',
                            labelWidth: 85
                        },
                        {
                            xtype: 'datefield',
                            padding: '0 0 0 5px',
                            fieldLabel: '创建时间(止)',
                            labelWidth: 85
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px 0 0',
                            fieldLabel: '首页显示',
                            labelWidth: 70
                        },
                        {
                            xtype: 'panel',
                            colspan: 3,
                            border: false,
                            layout: {
                                align: 'stretch',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    width: 70,
                                    text: '重置'
                                },
                                {
                                    xtype: 'button',
                                    margins: '0 0 0 10px',
                                    width: 70,
                                    text: '搜索'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    height: 250,
                    id: 'courseGrid',
                    width: 400,
                    title: '课程列表',
                    store: 'CourseGridStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '#',
                            text: '#'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '课程名称',
                            text: '课程名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '课程描述',
                            text: '课程描述'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '课时',
                            text: '课时'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '学分',
                            text: '学分'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '所属分类',
                            text: '所属分类'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '首页显示',
                            text: '首页显示'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '创建者',
                            text: '创建者'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '创建时间',
                            text: '创建时间'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'CourseGridStore'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    flex: 1,
                    items: [
                        {
                            xtype: 'button',
                            text: '添加课程'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});