/*
 * File: app/view/UserManageView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RLM.view.UserManageView', {
    extend: 'Ext.panel.Panel',

    id: 'UserManageModule',
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: '用户管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            action: 'importUserAction',
                            text: '导入用户模板'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            action: 'downloadUserTmplAction',
                            text: '下载用户导入模板'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    flex: 0,
                    height: 96,
                    id: 'userSearchForm',
                    layout: {
                        columns: 4,
                        type: 'table'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '0 5px 0 0',
                            fieldLabel: '帐号',
                            labelWidth: 35
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '真名',
                            labelWidth: 35
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px',
                            fieldLabel: '性别',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 5px',
                            fieldLabel: '邮箱',
                            labelWidth: 35,
                            inputType: 'email'
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px 0 0',
                            fieldLabel: '角色',
                            labelWidth: 35
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '学号',
                            labelWidth: 35
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px',
                            fieldLabel: '入学年份',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 5px',
                            fieldLabel: '电话',
                            labelWidth: 35
                        },
                        {
                            xtype: 'panel',
                            colspan: 4,
                            border: false,
                            layout: {
                                align: 'stretch',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    action: 'resetAction',
                                    width: 70,
                                    text: '重置'
                                },
                                {
                                    xtype: 'button',
                                    action: 'searchAction',
                                    margins: '0 0 0 10px',
                                    width: 70,
                                    text: '搜索'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    id: 'userGrid',
                    title: '用户列表',
                    store: 'UserGridStore',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'UserGridStore'
                        },
                        {
		                    xtype: 'toolbar',
		                    dock: 'top',
		                    items: [
		                        {
		                            xtype: 'button',
		                            action: 'addUserAction',
		                            text: '新增'
		                        },
		                        {
		                            xtype: 'tbseparator'
		                        },
		                        {
		                            xtype: 'button',
		                            action: 'delUserAction',
		                            text: '删除'
		                        }
		                    ]
		                }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '#',
                            text: '#'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '帐号',
                            text: '帐号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '密码',
                            text: '密码'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '真名',
                            text: '真名'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '性别',
                            text: '性别'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '邮箱',
                            text: '邮箱'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '角色',
                            text: '角色'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '学号',
                            text: '学号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '入学年份',
                            text: '入学年份'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '电话',
                            text: '电话'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '创建时间',
                            text: '创建时间'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});